gateway:
  clientId: bpmsClientId
  clientSecret: bpmsClientSecret

server:
  port: 8585
  servlet:
    context-path: /spring-security-oauth-server


spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: authentication_server_DB
  #      username:
  #      password:
  jackson:
    property-naming-strategy: SNAKE_CASE

#logging:
#  level:
#    org.springframework.security: DEBUG